version: '3.8'

services:
  db:
    build: ./db  
    container_name: globant_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi_service
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app 