version: '3.8'

services:
  db:
    build: ./db  # Construye la imagen usando el Dockerfile en la carpeta db
    container_name: globant_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"