version: '3.8'

services:
  db:
    build: ./db  
    container_name: globant_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi_service
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app 

  postgres_airflow:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  webserver:
    image: apache/airflow:2.10.5-python3.9
    restart: always
    depends_on:
      - postgres_airflow 
    env_file:
      - ./airflow/.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "-c", "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver"
    ]

  scheduler:
    image: apache/airflow:2.10.5-python3.9
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres_airflow
    env_file:
      - ./airflow/.env
    entrypoint: ["/bin/bash", "-c", "
      airflow scheduler"
    ]
    volumes:
      - ./airflow/dags:/opt/airflow/dags