CREATE TABLE IF NOT EXISTS departments (
    id SERIAL PRIMARY KEY,
    department VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS jobs (
    id SERIAL PRIMARY KEY,
    job VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS hired_employees (
    id SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "datetime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    department_id INTEGER NOT NULL,
    job_id INTEGER NOT NULL,
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    CONSTRAINT fk_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

-- TODO ¿INDICES?